### ISSUE TITLE
Redundant HID implementation 

### ISSUE THREAD

**Issue by noseglasses** [keyboardio/Kaleidoscope-Bundle-Keyboardio#20]
The files `HID.h` and `HID.cpp` are redundantly defined in library `HID` and `KeyboardioHID`.
Diffing them shoes that both are almost identical. Is there a particular reason for this redundancy or could the `HID` library possibly be removed from the bundle?

**Comment by obra** [comment]
I recall something about this, but not much detail. Does git history tell
you anything useful?

**Comment by algernon** [comment]
I _think_ the reason we have `HID` is that some parts of Arduino wants that, and were compiled before `KeyboardioHID` was pulled in. I may very well be wrong, though. I guess one way to find out would be to drop `HID` and see if anything breaks.

**Comment by obra** [comment]
Git history says:

commit 4df7064089175d5e97687e4f655a1e5a03ff477b
Author: Gergely Nagy <algernon@keyboard.io>
Date:   Fri Apr 19 23:03:23 2019 +0200

    Copy HID.h and HID.cpp over

    We depend on our version of these, tightly. To make it easier to add new
    features to the HID class itself, lets move it here. Arduino seems to
prefer the
    local copy over the built-in library, if both are present, so this
should be safe.

    Signed-off-by: Gergely Nagy <algernon@keyboard.io>


That suggests to me that we should be -removing- the separate HID library.
Anyone feel like testing that?
ᐧ

**Comment by noseglasses** [comment]
I am going to give it a try.

**Comment by noseglasses** [comment]
The HID library is unused by the build. Two firmware binaries (default Model01 sketch) build with and without HID (after removing it) are identical. I submitted https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio/pull/21 that removes it.

**Comment by algernon** [comment]
Since #21 has been merged, this can be closed too.
